```{r}
library(this.path)
setwd(this.path::here())

library(dplyr)
library(ggplot2)
library(lubridate)
library(stringr)
library(tidytext)
library(tm)
library(tidyr)

# --- Load the dataset ---
# Assuming 'property_transaction_victoria.csv' is in the same directory as your R script
df <- read.csv("git_ignore/property_transaction_victoria.csv", stringsAsFactors = FALSE)

# Convert relevant columns to appropriate types
df$sold_date <- as.Date(df$sold_date)
df$auction_date <- as.Date(df$auction_date)
df$available_date <- as.Date(df$available_date)

# Convert price, building_size, land_size to numeric.
# Coerce non-numeric values to NA and warn.
df$price <- as.numeric(gsub("[^0-9.]", "", df$price))
df$building_size <- as.numeric(gsub("[^0-9.]", "", df$building_size))
df$land_size <- as.numeric(gsub("[^0-9.]", "", df$land_size))


```

```{r}

library(this.path)
setwd(this.path::here())

library(dplyr)
library(ggplot2)
library(lubridate)
library(stringr)
library(tidytext)
library(tm)
library(tidyr)

# Assuming 'property_transaction_victoria.csv' is in the same directory as your R script
df <- read.csv("git_ignore/filtered_complaints.csv", stringsAsFactors = FALSE)

```
```{r}
str(df$Date_received)
```